### ISSUE TITLE
changing starting/ending hour and hour division

### ISSUE THREAD

**Issue by orangebutblue** [11notes/docker-ics-view#3]
How can I change these values like in the original project?

In niccokunzmann's version you could simply set these values:
`...starting_hour=7&amp;ending_hour=20&amp;hour_division=2&amp;...`

This way you didn't see the entire calendar from 0 to 24, but only during the timeframes that you wanted to.
And having an hourly division merges events that are too close too each other in a way that you can't read the title of both events

**Comment by orangebutblue** [comment]
I've also tried adding these attributes to the URL directly:

http://server:5000/?hour_division=2&tab=month

while hour_division doesn't work, tab=month does work. Same with starting_hour and ending_hour. They both don't work if you attach them to the URL

**Comment by 11notes** [comment]
My version onyl works with json files, you have to add it in json not the url, the URL only takes the json configuration, nothing else (located in /etc). There is also a default.json in this repo to check some settings.
`
{
  "starting_hour": 7,
  "ending_hour": 20,
  "hour_division":2
}
`

**Comment by orangebutblue** [comment]
I've tried adding these three attributes to the default.json, but it just doesn't work. They seem to have no effect

![image](https://user-images.githubusercontent.com/4688096/232015933-2271ea3f-8221-47b0-967f-722c27a0af3b.png)

As you can see from the picture, neither the starting hour works nor the hour division

Here is an excerpt from the default.json

```
{
  "description": "calendar",
  "template": "dhtmlx.html",
  "skin": "dhtmlxscheduler_material.css",
  "loader": "/img/loaders/circular-loader.gif",
  "target": "_top",
  "timeshift": 0,
  "language": "de",
  "tab": "week",
  "tabs": [
    "month",
    "week",
    "day",
    "agenda"
  ],
  "controls": [
    "next",
    "previous",
    "today",
    "date"
  ],
  "starting_hour": 7,
  "ending_hour": 20,
  "hour_division": 2,
...
```

Changing any other setting in the default.json works flawlessly. But just those three values seem to not work at all for some reason
