### ISSUE TITLE
Missing docker/release tags

### ISSUE THREAD

**Issue by seraphx2** [11notes/docker-ics-view#4]
My TrueNAS Scale app was being redeployed and it tried to pull tag 5.1.6. Apparently, that tag no longer exists? What happened to that tag? why is the only one available 1.4 now?

**Comment by 11notes** [comment]
yeah let me clean this up, I was in the process of changing the "forking" of the original repo because there are too many small changes in some places, let me fix this today with the newest release from the original repo.

**Comment by seraphx2** [comment]
any traction on this?

**Comment by 11notes** [comment]
ah shit I saw he made a few more changes so I have to adopt way more than I anticipated. I’m working today on it to see if I can get it going again with the newest version of his repo.

**Comment by 11notes** [comment]
I've added the newest version 1.13 on the current build of https://github.com/niccokunzmann/open-web-calendar. You might have to check your configuration json, there is now more data available, both examples in the repo show what you can configure, more info on the original repo.
