### ISSUE TITLE
License GPLv2

### ISSUE THREAD

**Issue by niccokunzmann** [11notes/docker-ics-view#6]
Hi, I can see the app.py file in the project. That one is under GPLv2 as well as other code I wrote.

**Comment by 11notes** [comment]
Hi,

Thanks for your great work. I modified your code to a degree that it's not your code anymore. You can check the deltas yourself.

**Comment by niccokunzmann** [comment]
Thanks for your fast response. Have a look at this: https://softwareengineering.stackexchange.com/q/254046
I read it as that you are not even allowed to modify the code if the license is not obeyed and in that license it is said that the license text/header shall be with the code.

The project can also be dual-licensed and also just for the files you modified. MIT+GPLv2.

I can understand that you have hesitations to work on this. Either way, the license grants modification and based on this, the modifications do not take you out of the license.
